компонент input формы useFormik
evaliev/loan_web_app_bot pull request #16
Opened 2022-12-05 11:31 UTC by AlexCherepanov86

2022-12-05 11:53 UTC, Flydist requested changes

2022-12-05 11:53 UTC, Flydist commented on src/pages/OwnerPage/index.tsx
> +        <FormInput type="text" name="date" label="Фамилия" id="" />
id="" выглядит очень криво

2022-12-05 12:04 UTC, Flydist commented on src/components/Form/FormInput/FormInput.tsx
> +        onChange={form.handleChange}
Возможно придется прокинуть хендлеры, а тут мы используем только формиковский. Сейчас думаю нужно забить, потому что не получится нормально состыковаться нам всем, по факту придется решать

2022-12-05 13:07 UTC, Flydist requested changes

2022-12-05 13:07 UTC, Flydist commented on src/components/Form/FormInput/FormInput.tsx
> +      {form.touched.name && form.errors.name ? (
Валидация валит сразу всю форму, не работает touched, проверил

2022-12-05 13:07 UTC, Flydist commented on src/pages/LentData/index.tsx
> +  const submit = () => console.log('submit');
Нужно добавить телеграмовскую кнопку и повесить туда сабмит. И на handleBack придумать, что делать

2022-12-05 13:07 UTC, Flydist commented on src/components/Form/FormInput/FormInput.tsx
> +        id={id}
Можно если id не прокинут прокидывать name

2022-12-05 13:32 UTC, AlexCherepanov86 commented on src/pages/OwnerPage/index.tsx
> +        <FormInput type="text" name="date" label="Фамилия" id="" />
по идее можно к нейму цепляться, можно убрать

2022-12-05 13:33 UTC, AlexCherepanov86 commented on src/components/Form/FormInput/FormInput.tsx
> +        onChange={form.handleChange}
yeap

2022-12-05 13:40 UTC, Flydist commented on src/components/Form/FormInput/FormInput.tsx
> +        onChange={form.handleChange}
Зря написал забить, нужно всем вместе просто обсудить

2022-12-06 13:38 UTC, Flydist approved these changes

2022-12-06 13:39 UTC, Flydist approved these changes

2022-12-06 14:58 UTC, merged